// <auto-generated />
using Labb3_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(Labb3DbContext))]
    [Migration("20240425094356_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestID = 100,
                            Description = "Playing video games",
                            Title = "Gaming"
                        },
                        new
                        {
                            InterestID = 101,
                            Description = "Any type of exercise like running, sports or gym",
                            Title = "Exercise"
                        },
                        new
                        {
                            InterestID = 102,
                            Description = "Reading books",
                            Title = "Reading"
                        },
                        new
                        {
                            InterestID = 103,
                            Description = "Following the different football leauges in Europe",
                            Title = "Football"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserInterestLinkID")
                        .HasColumnType("int");

                    b.HasKey("LinkID");

                    b.HasIndex("UserInterestLinkID");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkID = 50,
                            URL = "www.youtube.com",
                            UserInterestLinkID = 1
                        },
                        new
                        {
                            LinkID = 51,
                            URL = "www.transfermarkt.com",
                            UserInterestLinkID = 1
                        },
                        new
                        {
                            LinkID = 52,
                            URL = "www.books.com",
                            UserInterestLinkID = 2
                        },
                        new
                        {
                            LinkID = 53,
                            URL = "www.running.com",
                            UserInterestLinkID = 2
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            PhoneNumber = "1234567",
                            UserName = "Noah"
                        },
                        new
                        {
                            UserID = 2,
                            PhoneNumber = "1234567",
                            UserName = "Simon"
                        },
                        new
                        {
                            UserID = 3,
                            PhoneNumber = "1234567",
                            UserName = "Casper"
                        },
                        new
                        {
                            UserID = 4,
                            PhoneNumber = "1234567",
                            UserName = "Svante"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterestLink", b =>
                {
                    b.Property<int>("UserInterestLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserInterestLinkID"));

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserInterestLinkID");

                    b.HasIndex("InterestID");

                    b.HasIndex("UserID");

                    b.ToTable("UserInterestLinks");

                    b.HasData(
                        new
                        {
                            UserInterestLinkID = 1,
                            InterestID = 100,
                            UserID = 1
                        },
                        new
                        {
                            UserInterestLinkID = 2,
                            InterestID = 102,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.UserInterestLink", "UserInterestLink")
                        .WithMany("Links")
                        .HasForeignKey("UserInterestLinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInterestLink");
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterestLink", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", "Interest")
                        .WithMany("UserInterestLinks")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.User", "User")
                        .WithMany("UserInterestLinks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("UserInterestLinks");
                });

            modelBuilder.Entity("Labb3_API.Models.User", b =>
                {
                    b.Navigation("UserInterestLinks");
                });

            modelBuilder.Entity("Labb3_API.Models.UserInterestLink", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
